backend:
  name: git-gateway
  branch: main 

display_url: https://blog.try-qr.com
publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Məqalələr"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlıq", name: "title", widget: "string"}
      - {label: "Məzmun", name: "body", widget: "markdown"}
