backend:
  name: github
  repo: FaridFatullayefh/try-qr-blog
  branch: main
  base_url: https://try-qr-auth.faridfatullayefh.workers.dev
  auth_endpoint: auth
  
display_url: https://blog.try-qr.com
publish_mode: editorial_workflow

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Məqalələr"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlıq", name: "title", widget: "string"}
      - {label: "Məzmun", name: "body", widget: "markdown"}
